### ISSUE TITLE
Does not filter out personal folders

### ISSUE THREAD

**Issue by jagger** [DelineaXPM/delinea-platform#141]
https://github.com/DelineaXPM/delinea-platform/blob/94aca686dcf3f80e7fb6b657c4400c10373b33c2/Reports/SecretServer/PlatformMigration/Platform_Migration_Inventory.sql#L594

**Comment by ConagherL** [comment]
This item has been fixed with the latest changes

**Comment by tylerezimmerman** [comment]
This was resolved in #140
